name: Subir mi sitio al repositorio público

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkoutear repositorio
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            docs

      - name: Copiar docs al directorio para subir
        run: |
          mkdir public_repo
          cp -r docs/* public_repo/

      - name: Inicializar y empujar al repo público
        run: |
          cd public_repo
          git init
          git config --global user.email "mir123@gmail.com"
          git config --global user.name "mir123"
          git remote add origin https://github.com/mir123/miramapas.git
          git add .
          git commit -m "Subida auto de sitio construido"
          git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
